FROM postgres:16

RUN apt-get update && apt-get install -y \
    git \
    make \
    gcc \
    postgresql-server-dev-16

RUN git clone --depth 1 https://github.com/pgvector/pgvector.git /pgvector \
  && cd /pgvector \
  && make && make install \
  && rm -rf /pgvector
